---
- name: Minikube with Knative
  hosts: localhost
  connection: local

  collections:
    - community.kubernetes

  vars:
    k8s_cluster_ip: "{{ ansible_env.MINIKUBE_IP | default('127.0.0.1') }}"
    minikube_profile_name: "{{ ansible_env.PROFILE_NAME }}"
    deploy_ingress: True
    deploy_knative: True

  roles:
    - role: kameshsampath.k8s_app_spices