---
- name: Add Skupper Site Controller
  hosts: localhost
  connection: local

  collections:
    - community.kubernetes

  vars:
    skupper_manifests_dir: /tmp/skupper/tasks

    manifests:
      - name: skupper-site-controller
        manifest_url: "https://raw.githubusercontent.com/skupperproject/skupper/0.3/cmd/site-controller/deploy-watch-all-ns.yaml"
        target_namespace: skupper-site-controller
  
  tasks:
    - name: Create Manifests Dir
      file:
        path: "{{ skupper_manifests_dir }}"
        state: directory

    - name: Download Manifests
      get_url:
        url: "{{ item.manifest_url }}"
        dest: "{{ [skupper_manifests_dir,item.name] | join('/') }}.yaml"
        mode: "666"
      with_items: 
       - "{{ manifests }}"

    - name: Create Manifests namespace
      community.kubernetes.k8s:
        state: present
        kind: Namespace
        name: "{{ item.target_namespace }}"
      with_items: 
        - "{{ manifests }}"

    - name: Apply Manifests
      community.kubernetes.k8s:
        state: present
        src: "{{ [skupper_manifests_dir,item.name] | join('/') }}.yaml"
        namespace: "{{ item.target_namespace }}"
      with_items: 
        - "{{ manifests }}"